### EE-230 Assignment ( Topic- Freivald Algorithm)
- **Name: Ravi Saini**
- **Roll No: 210102069**

## Freivald Algorithm:
 The Freivalds algorithm is a randomized algorithm used to verify whether a matrix multiplication has been computed correctly or Not.We have Given three matrices $A$, $B$, and $C$, each of dimensions $n x n$,then the algorithm checks whether $AB$  is equal to $C$ or Not, where $A$, $B$, and $C$ are given matrices of integers.

### Algorithm works as follows:
 - Choose a random vector $r$ of $0$s and $1$s, of length n.
 - Compute the product $Br$ of the matrix $B$ with the random vector $r$.
 - Compute the product $ABr$ of the matrix $A$ with the vector $Br$.
 - Compute the product $Cr$ of the matrix C with the random vector $r$.
 - Check whether the product $ABr$ and $Cr$ is equal or Not.

###### Error in algorithm:
**The algorithm has a probability of error of $1/2$, meaning that if $AB ≠ C$, it correctly identifies the error with probability $1/2$.** However,**if AB = C, the algorithm always returns the correct answer.** The running time of the algorithm is $O(kn^2)$, where k is a constant factor that depends on the desired probability of error.

###### Reduce error in Algorithm:
To reduce the error of the Freivalds algorithm,we can run it multiple times and take the majority vote of the results. By running the algorithm multiple times, we can reduce the probability of error. For example,**if we run the algorithm k times, the probability of error becomes $2^{-k}$**. So, by increasing the number of times we run the algorithm, we can reduce the error probability to an arbitrarily small value.

## Freivald Algorithm Python Code:
- **take matrices size $n<=1000$ so code run efficiently**.

In [34]:
import random
import numpy as np
import time

The Function **freivald($A$,$B$,$C$,$k$)** Take $4$ values as input, matrices $A$,$B$ and $C$ and a integer $k$ equal to number of iteration you want to reduce error by $2^{-k}$ and return **True** or **False**.

In [35]:
#freivald algorithm function 
#here k is number of iteration you want to increase the probability of getting right answer
def freivald(A, B, C,k):
    n = len(A)
    for i in range(k):
        r = [random.randint(0, 1) for _ in range(n)]
        Br = np.dot(B,r);
        ABr = np.dot(A,Br)
        Cr = np.dot(C,r)
        print("Vector r is:",r)
        print("vector B*r is:",Br)
        print("Vector C*r is:",Cr)
        if not np.array_equal(ABr, Cr):
            return False
    return True     


In the bolow code we can select the size of matrices$ A$ and $B$ by changing value of$n$ in code, then generate $A$ and $B$ using python inbuild functions and compute the result $A$ dot $B$ and store in matrix $C$.

In [58]:
# Test the implementation on larger matrices
#select any size you want by change value of n
n = 900

#create matrices A and B using python functions
A = np.random.randint(10, size=(n, n))
B = np.random.randint(10, size=(n, n))

time1 = time.time() #catch start time of dot product
C = A.dot(B)
time2 = time.time()  #catch end time of dot product

Print Matrices $A$,$B$ and $C$:

In [46]:
#Print all three matrices A,B and C
print("Matrix A :",A)
print("Matrix B :",B)
print("Matrix C :",C)

Matrix A : [[6 5 4 ... 2 3 8]
 [5 9 0 ... 7 5 3]
 [4 4 2 ... 3 0 6]
 ...
 [1 7 4 ... 8 3 5]
 [0 2 0 ... 3 1 7]
 [4 2 6 ... 0 9 4]]
Matrix B : [[9 5 9 ... 9 0 5]
 [7 6 3 ... 5 8 9]
 [8 9 2 ... 5 3 3]
 ...
 [3 5 9 ... 8 3 8]
 [8 2 8 ... 4 2 5]
 [0 9 8 ... 4 5 4]]
Matrix C : [[8047 8139 8310 ... 8372 8567 8271]
 [7909 8217 8128 ... 8153 8574 8544]
 [7510 7819 7831 ... 7996 8550 7876]
 ...
 [8295 8488 8712 ... 8539 8833 8588]
 [7861 8080 7892 ... 8296 8738 8640]
 [7568 7570 7615 ... 7690 7740 7674]]


We can change value of $k$ for reduce error in result, first we take $k$=1$0$ which reduce our error to $2^{-10}$% approximately equal to $0.1$%.

In [59]:
start_time = time.time() #catch the start time of freivald algorithm
result = freivald(A, B, C,10)  #store the result of algorithm in result variable 
end_time = time.time() #catch the start time of freivald algorithm

Vector r is: [0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,

**Print the result provided by freivald algorithm** and **time comparision of freivald algorithm** and **dot product** 

### Time Comparision:
When we verify matrix multiplication by **dot product so it takes much time for large matrices compare to freivald algorithm**, because in freivald algorithm we take dot product with $1$-$D$ vector to verify multiplication on the place of given $2$-$D$ size matrices, ehich reduces our time more when we move towards large size $2$-$D$ matrices.


In [60]:
print("Result:", result)
print("Elapsed time in freivald algorithm:", end_time - start_time, "seconds")
print("Elapsed time in Dot product:", time2 - time1, "seconds")

Result: True
Elapsed time in freivald algorithm: 0.12198209762573242 seconds
Elapsed time in Dot product: 2.2436635494232178 seconds


### We can check algorithm saves time for large matrices by run the code for diffrent values of n. 

- **A table with time comparision for diffrent matrices size (n)**:
| Size of Matrices ($n*n$) | algorithm time(in s) | dot-product time (in s) |
|----------|----------|----------|
| $1*1$ | 0.00199| 0.00000  |
| $10*10$ | 0.00299 | 0.00000 |
|$100*100$ | 0.01309 | 0.000997|
|$200*200$ | 0.02745 | 0.00601|
|$300*300$ | 0.03801 | 0.03155 |
|$400*400$ | 0.04966 | 0.07089|
|$500*500$ | 0.06868| 0.19004|
|$600*600$ |0.08331 | 0.26261|
|$700*700$ | 0.06883 |0.63414 |
|$800*800$ | 0.08323 | 1.16856|
|$900*900$ | 0.12198 |2.24366 |
| $1000*1000$ | 0.15242| 2.88602 |


### Plot graph comaring time taken by algorithm and dot product with respect to soe of matrices
- **use matplotlib library of python for plot the graph.**
- size_n : store size values of matrices
- time_algorithm : store time taken by freival algorithm for diffrent matrices size
- time_dotproduct : store time taken by dot product for diffrent matrices size

In [2]:
import matplotlib.pyplot as plt

# Data
size_n = [1, 10, 100, 200, 300,400,500,600,700,800,900,1000]  # size of matrices

# time taken by algorithm
time_algorithm = [0.00199, 0.00299,  0.01309, 0.02745,  0.03801,0.04966,0.06868,0.08331 ,0.06883, 0.08323,0.12198,0.15242] 

# time taken by dot product
time_dotproduct = [0.00000, 0.00000,  0.000997, 0.00601, 0.03155,0.07089,0.19004,0.26261,0.63414,1.16856,2.24366,2.88602 ]

# Plotting the graph
plt.plot(size_n, time_algorithm, label='Time taken by algorithm')
plt.plot(size_n, time_dotproduct, label='Time taken by dot product')

# Adding labels and title
plt.xlabel('Size of matrices (n)')
plt.ylabel('Time taken (in seconds)')
plt.title('Comparison of Time taken by alforithm and dot product on Y-axis with respect to size of matrices on X-axis')

# Adding legend
plt.legend()

# Showing the plot
plt.show()


## Conclusion:
- **As we show in graph time taken by algorithm is very less compare to dot product for large matrices so we conclude that algorithm saves time for large matrices**.